### ISSUE TITLE
Second Demo Build - Text on the wall in Delivery 2 is not flush with the wall. 

### ISSUE THREAD

**Issue by JakeRe** [Kobakat/GrappleGame#174]
![TextBugInDelivery2](https://user-images.githubusercontent.com/44097843/114079553-f4c0cd00-986f-11eb-8b77-019f857b8941.png)

### Steps to Replicate
1.Player gets toward the end of delivery two and goes up against the wall. 

### Current Outcome 
The text is floating in the air without explanation. 

### Expected Outcome
Text is flush with the wall.

**Comment by Error404Danny** [comment]
Has been fixed. Moving any further against the wall will make the text disappear.
