### ISSUE TITLE
Second Demo Build - Cranes in Delivery 4 do not match grappleable nature of Delivery 3

### ISSUE THREAD

**Issue by JakeRe** [Kobakat/GrappleGame#183]
![ProblemWithCollision](https://user-images.githubusercontent.com/44097843/114217518-e802ae80-992d-11eb-9a3c-a0225c47c6a4.png)

### Steps to Replicate
1. Player enters Delivery 4
2. Player attempts to grapple to a crane, however they cannot grapple to it. 

### Current Outcome 
1. Player can't grapple to cranes. 

### Expected Outcome
1. Player would be able to grapple onto the cranes due to their previous experiences in Delivery 3.

**Comment by Error404Danny** [comment]
All cranes have grappleable sections.
