### ISSUE TITLE
Second Demo Build - Player falls down for too long when they miss a grapple

### ISSUE THREAD

**Issue by JakeRe** [Kobakat/GrappleGame#184]
### Steps to replicate
1. Player will attempt to grapple to a point in Delivery 4
2. Player will miss and fall. 

### Current Outcome 
1. Player falls down for around six seconds. 

### Expected Outcome
1. I would be able to play for more time than I am falling.

**Comment by Kobakat** [comment]
Decrease the Z axis of the in bounds box @Error404Danny

**Comment by Error404Danny** [comment]
Fixed out of bounds as well as location of the fog to hide the missing floors
