### ISSUE TITLE
Demo Build 3 - Player will not correctly teleport up in Tutorial Sequence. 

### ISSUE THREAD

**Issue by JakeRe** [Kobakat/GrappleGame#244]
### Steps to recreate 
1. Player will get to the area where they run the risk of falling and missing a ledge. This is to test the reeling of the grapple gun. 
2. Player will release the grapple in an attempt to land on the platform. 
3. Player will miss and land to the left or right of the platform. 

### Expectation 
I will be sent back up to the platform I need to be on to try again.

### Current Outcome 
I am not able to be sent back up unless I move toward the wall.
![TutorialBug1](https://user-images.githubusercontent.com/44097843/116751082-1faec480-a9c9-11eb-9a83-8a7920ae108e.png)

**Comment by JSchoppe** [comment]
Collider was not covering the entire region; fixed in recent audio push.
