### ISSUE TITLE
Demo Build 3 - Tutorial Voice Lines Play Over Each Other Or Double If the Player Runs Too Fast. 

### ISSUE THREAD

**Issue by JakeRe** [Kobakat/GrappleGame#251]
### Steps to Recreate
1. Player "speed runs" the tutorial by sprinting the entire time that they're moving 

### Expectation 
1. Voice lines will play only once when the player goes through the tutorial. 

### Current Outcome 
1. Voice lines that tell the player what to do overlap.

**Comment by JSchoppe** [comment]
Solved with new audio singleton that manages audio requests and avoids audio stacking whenever possible.
